.gitignore, build, docker/Dockerfile, docker/ep, docker/repos.vendor
=> Docker: Added docker repo and build script

api, app, config, coog, defaults/nginx.conf, net, nginx, paybox, postgres, redis, sentry, upgrade
=> docker link -> docker network

docker/ep
add daily_chains to docker entrypoint to call daily_chains from docker
=> coog-admin: support calling docker from entrypoint

backup
=> backup: changed generated archive filenames to avoid overwriting

upgrade
=> upgrade: search and pull from docker hub

config, coog, images/coog/ep, upgrade
Attention, cela change l'utilisation de upgrade !!!
Fix #6946
=> add config items for workers nb

backup
=> backup: fix attachments dump issue and add process info during execution

coog, images/coog/Dockerfile, images/coog/ep
eg. in ./edit-config you can specify an environment variable like so:
`MOUNT="//SERVER/src:/dest/:options;//SERVER2/src2:/dest2/:options"`
=> add option to mount cifs server when running coog container

backup
=> backup: handle specific backup dates on weekday

config, defaults/config, defaults/nginx/nginx.conf, defaults/nginx/nginx_server.conf, defaults/nginx/nginx_server_letsencrypt.conf, defaults/nginx/nginx_server_ssl.conf, defaults/nginx/server-coog-ssl.conf, defaults/nginx/server-web.conf, nginx, ssl/CUSTOM_KEYS/init, ssl/LETSENCRYPT/init, ssl/LETSENCRYPT/nginx_min/nginx.conf
=> coog-admin: Possibility to use certificate for https connection with NGINX

defaults/nginx/server-coog.conf, images/build-utils.sh, images/coog/Dockerfile
=> coog-admin: add documentation generation in docker images build

defaults/nginx/server-coog-ssl.conf, defaults/nginx/server-coog.conf, nginx
=> coog-admin: Ensure https redirection

images/coog/Dockerfile
=> coog-admin: Freeze pip version in Dockerfile

backup, coog, nginx, postgres, redis
=> separate volumes where container tmp is mapped

CHANGELOG, README.md, backup, bi, config, config.fn, coog, defaults/config, dwh, edit-config, etl, init, net, nginx, paybox, postgres, pull, redis, sentry, ssl/CUSTOM_KEYS/init, ssl/LETSENCRYPT/init, sync, upgrade, web
=>  put coog-data under a standalone git repo

config, config.fn, nginx
=> check web on nginx launch

backup, bi, conf, config, coog, dwh, etl, init, net, nginx, paybox, postgres, pull, redis, sentry, sync, upgrade, web
=> check COOG_CODE_DIR is a folder + improve error message + remove cron from upgrade

config, coog, dwh, images/coog/3-alpine/Dockerfile, images/coog/3/Dockerfile, images/coog/Dockerfile, images/coog/ep, images/coog/py3/Dockerfile, images/unoconv/Dockerfile, images/unoconv/build, nginx, postgres, pull, redis, unoconv, upgrade
=> coog py3 image and separate unoconv image

config, coog, images/coog/3-alpine/Dockerfile, images/coog/3/Dockerfile, images/coog/Dockerfile, images/coog/ep, images/coog/repos.vendor, test
=> test: new command to test coog image

config, coog, images/coog/ep
=> report: set a default report config

images/build-utils.sh
=> build: based on tag

CHANGELOG, images/coog/ep, postgres
=> coog-admin : add anon_dump command

coog, images/coog/ep, images/web/Dockerfile, images/web/ep, upgrade, web
=> web: add version command

images/build-utils.sh
=> clean git ignored files from clones after build

test
=> coog-admin: pull coog-admin on test

CHANGELOG, defaults/nginx/nginx_server_letsencrypt.conf, defaults/nginx/nginx_server_ssl.conf
=> nginx: increase ssl security

images/build-utils.sh
=> guess whether we build on a branch / tag

config.fn
=> confirm branch creation on data

CHANGELOG, defaults/nginx/server-coog.conf
=> nginx: restrict access to sao and bench

postgres
=> postgres: binary dump by default

doc/coog_deployment_with_coog_admin.md
=> Add documentation about coog data folder

backup, images/coog/2-alpine/Dockerfile, images/coog/3-alpine/Dockerfile, images/coog/ep
=> Add script ep load with bash

start_coog
=> start_coog: add memory limit

CHANGELOG, config, doc/coog_deployment_with_coog_admin.md, unoconv
=> unoconv: Make server fonts available

CHANGELOG, images/coog/ep
=> Batch report commands

CHANGELOG, images/coog/2-alpine/Dockerfile, images/coog/3-alpine/Dockerfile, images/coog/3/Dockerfile, images/coog/Dockerfile
=> images: Add phonenumbers in docker images

coog_batch_exec
=> coog-admin: add memory to batch exec

config, redis
=> Add redis extra args env

backup
=> Fix space usage

CHANGELOG, backup
=> Fix cp of attachment

CHANGELOG, README.md, config, doc/oauth_setup.md, web
=> Add Config for web applications

images/coog/3/Dockerfile, images/coog/Dockerfile
=> Update ldap3 version in dependencies

start_coog
=> set memory limit at 5g for redis

postgres
Also fix user and password for client in case COOG_POSTGRES_HOST is defined
=> postgres: use POSTGRES_USER and POSTGRES_PASSWORD for anon_dump. 

CHANGELOG, doc/coog_deployment_with_coog_admin.md, doc/upgrade_1.2_to_2.0.rst, doc/upgrade_coog_env.md, upgrade
=> Remove volumes when stopping / restarting a container

docker/Dockerfile
=> Update dependencies for 1.12

CHANGELOG, images/web/Dockerfile, images/web/ep
=> Web: [2.0] Allow to add customs repositories

CHANGELOG, backup, images/web/ep
=> Web: Fix typo in repo link

images/coog/3/Dockerfile, images/coog/Dockerfile
=> docker: fix redis dependency issue

images/coog/Dockerfile
=> dockerfile: change celery to celery[redis]

CHANGELOG, images/build-utils.sh
Ref #11411
Pull request semi lié a https://github.com/coopengo/coog/pull/2712/
=> Handle doc generation with docker (docker-compose)

images/coog/docker/coog/Dockerfile
See : https://github.com/celery/kombu
the Kombu issue is 1087
=> DockerFile: set celery version to 4.3.0 and kombu to 4.6.3

images/coog/Dockerfile
=> Fix kombu version to 4.6.3

backup
=> backup: remove date from daily attachment archive name

images/portal/docker-compose.yml, images/portal/docker/api-identity-manager/Dockerfile, images/portal/docker/gateway/Dockerfile, portal
=> Portal: Separate identity server from gateway container

images/coog/docker/coog/Dockerfile
=> coog-amin: Container Users Coreye complient
